apiVersion: v1
kind: Secret
metadata:
  name: jobboard-secrets
  namespace: jobboard
type: Opaque
data:
  # Paste your base64 values here
  MONGODB_URI:         bW9uZ29kYitzcnY6Ly9qb2Jib2FyZF91c2VyOjk0WFRYaE40UTBBOThCQXVAY2x1c3RlcjAuaHdrZm9yaS5tb25nb2RiLm5ldC8=
  JWT_ACCESS_SECRET:   YWRlODQ1ODZhOTUwZGRiM2VhZjAxZGNmMTU0NzM5YTkyNzY2OTc4ZmE2NjY2MDdmMGZmYWQwOWJmYzQ0ODE0NWJjZTAzZjI0YjEwNTk3NjY4MGJjMjg1NDRlNmVhOGRjZmVlYmY1YjBmOWMyMjdiNjllOTk0MjA1NzQ2YzZjNDc=
  JWT_REFRESH_SECRET:  NDJmY2UxOWZmZGJhODQyYjM4NTFhZDkzNjRjZDQwN2M5M2VhMmIzZjJiZTBlNjY2NjQxMTkwZGUzYWZmMzBhMGUyNzlkMDM3YzJkZDBmZGM1MmI1NTQ3ZjUzNTYyNDAwYTU4YjY2YzllZTkxNjk1NGM2Yzg0OTdiNDExMDRiMGM=